/*
 * Grafana HTTP API.
 *
 * The Grafana backend exposes an HTTP API, the same API is used by the frontend to do everything from saving dashboards, creating users and updating data sources.
 *
 * API version: 0.0.1
 * Contact: hello@grafana.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package go_client

// COMMANDS
type AddApiKeyCommand struct {
	CreateServiceAccount bool `json:"createServiceAccount,omitempty"`
	Name string `json:"name,omitempty"`
	Role *RoleType `json:"role,omitempty"`
	SecondsToLive int64 `json:"secondsToLive,omitempty"`
	ServiceAccount int64 `json:"serviceAccount,omitempty"`
}
