/*
 * Grafana HTTP API.
 *
 * The Grafana backend exposes an HTTP API, the same API is used by the frontend to do everything from saving dashboards, creating users and updating data sources.
 *
 * API version: 0.0.1
 * Contact: hello@grafana.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package go_client

// CreateDashboardSnapshotCommand is same as models.CreateDashboardSnapshotCommand but with swagger annotations
type CreateDashboardSnapshotCommand struct {
	Dashboard *simplejson.Json `json:"dashboard"`
	// Unique key used to delete the snapshot. It is different from the `key` so that only the creator can delete the snapshot. Required if `external` is `true`.
	DeleteKey string `json:"deleteKey,omitempty"`
	// When the snapshot should expire in seconds in seconds. Default is never to expire.
	Expires int64 `json:"expires,omitempty"`
	// Save the snapshot on an external server rather than locally.
	External bool `json:"external,omitempty"`
	// Define the unique key. Required if `external` is `true`.
	Key string `json:"key,omitempty"`
	// Snapshot name
	Name string `json:"name,omitempty"`
}
