/*
 * Grafana HTTP API.
 *
 * The Grafana backend exposes an HTTP API, the same API is used by the frontend to do everything from saving dashboards, creating users and updating data sources.
 *
 * API version: 0.0.1
 * Contact: hello@grafana.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package go_client

import (
	"time"
)

type SaveDashboardCommand struct {
	Result *Dashboard `json:"Result,omitempty"`
	UpdatedAt time.Time `json:"UpdatedAt,omitempty"`
	Dashboard *simplejson.Json `json:"dashboard,omitempty"`
	FolderId int64 `json:"folderId,omitempty"`
	FolderUid string `json:"folderUid,omitempty"`
	IsFolder bool `json:"isFolder,omitempty"`
	Message string `json:"message,omitempty"`
	Overwrite bool `json:"overwrite,omitempty"`
	UserId int64 `json:"userId,omitempty"`
}
