/*
 * Grafana HTTP API.
 *
 * The Grafana backend exposes an HTTP API, the same API is used by the frontend to do everything from saving dashboards, creating users and updating data sources.
 *
 * API version: 0.0.1
 * Contact: hello@grafana.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package go_client

import (
	"time"
)

// Dashboard model
type Dashboard struct {
	Created time.Time `json:"Created,omitempty"`
	CreatedBy int64 `json:"CreatedBy,omitempty"`
	Data *simplejson.Json `json:"Data,omitempty"`
	FolderId int64 `json:"FolderId,omitempty"`
	GnetId int64 `json:"GnetId,omitempty"`
	HasAcl bool `json:"HasAcl,omitempty"`
	Id int64 `json:"Id,omitempty"`
	IsFolder bool `json:"IsFolder,omitempty"`
	OrgId int64 `json:"OrgId,omitempty"`
	PluginId string `json:"PluginId,omitempty"`
	Slug string `json:"Slug,omitempty"`
	Title string `json:"Title,omitempty"`
	Uid string `json:"Uid,omitempty"`
	Updated time.Time `json:"Updated,omitempty"`
	UpdatedBy int64 `json:"UpdatedBy,omitempty"`
	Version int64 `json:"Version,omitempty"`
}
