/*
 * Grafana HTTP API.
 *
 * The Grafana backend exposes an HTTP API, the same API is used by the frontend to do everything from saving dashboards, creating users and updating data sources.
 *
 * API version: 0.0.1
 * Contact: hello@grafana.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package go_client

// DashboardAclUpdateItem is same as dtos.DashboardAclUpdateItem but with swagger annotations
type DashboardAclUpdateItem struct {
	// Permission level Description: `1` - View `2` - Edit `4` - Admin
	Permission int64 `json:"permission,omitempty"`
	Role *RoleType `json:"role,omitempty"`
	TeamId int64 `json:"teamId,omitempty"`
	UserId int64 `json:"userId,omitempty"`
}
