/*
 * Grafana HTTP API.
 *
 * The Grafana backend exposes an HTTP API, the same API is used by the frontend to do everything from saving dashboards, creating users and updating data sources.
 *
 * API version: 0.0.1
 * Contact: hello@grafana.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package go_client

// UpdateDashboardAclCommand is same as dtos.UpdateDashboardAclCommand but with swagger annotations
type UpdateDashboardAclCommand struct {
	// The permission items to add/update. Items that are omitted from the list will be removed.
	Items []DashboardAclUpdateItem `json:"items,omitempty"`
}
